language: ruby
rvm:
  - 2.5
  - 2.6
  - jruby
  - truffleruby

before_install:
  gem install overcommit

# command to install dependencies
install:
  - pip install -r requirements.txt
  - 
# command to run tests
script:
  - pytest
